---
title: Latent Semantic Analysis
subtitle: Ayush Noori
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: yes
editor_options: 
  chunk_output_type: inline
---

# Dependencies

Load requisite packages and define directories. Note that this script loads my personal utilities package, `ayushnoori/brainstorm`, which is available via GitHub.

```{r load-packages, message=FALSE, warning=FALSE}

# data manipulation
library(data.table)
library(purrr)
library(magrittr)
library(stringr)

# data visualization
library(ggplot2)

# source utilities script
library(brainstorm)

```

Directories are relative to the R project path.

```{r define-directores}

ddir = file.path("Results", "2 - Parse Tweets")
rdir = file.path("Results", "3 - Latent Semantic Analysis")

```

# Read Data

```{r read-data}

twt = readRDS(file.path(ddir, "Final Parsed Tweets.RDS"))

```

# Latent Semantic Analysis

First, discard unneeded columns.

```{r subset-columns}

# twt = tweets[, .(id, full_text, display_text_range, created_at, user, source, in_reply_to_status_id, in_reply_to_user_id, in_reply_to_screen_name, is_quote_status, quoted_status_id, retweeted, favorited, retweet_count, favorite_count, possibly_sensitive, entities, coordinates, place)]

```
